// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetVideoAudioUrl(arg1:string):Promise<string>;

export function SearchMusic(arg1:string):Promise<Array<types.Video>>;
