// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVideoAudioUrl(arg1) {
  return window['go']['main']['App']['GetVideoAudioUrl'](arg1);
}

export function SearchMusic(arg1) {
  return window['go']['main']['App']['SearchMusic'](arg1);
}
